---
title: "Backup"
author: "Mike"
date: "2023/3/23"
output:   pdf_document:
    latex_engine: lualatex
fontsize: 12pt
mainfont: Calibri Light
header-includes:
- \usepackage{setspace}\doublespacing
- \usepackage{fvextra}
- \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
my.dir <- dirname(rstudioapi::getActiveDocumentContext()$path)
setwd(my.dir) 
library(dplyr) #for dataset manipulation
library(ggplot2) #for creating graphs
library(patchwork) #for graphs with 2 y axes
library(hrbrthemes) #similar to the above
library(pwt10) #for the Penn World Tables -- load "pwt10.01"
library(countrycode) # for the country codes
data("pwt10.01") #be sure to left click "pwt10.01" in the values section in R
polity <- read.csv("data/p5v2018.csv")
```

## Backup
```{r, include=FALSE, results='asis'}
#creating a subset of the datasets to build the main dataset
df_penn_world <- pwt10.01%>% dplyr::select(country, isocode, year, rgdpna, rgdpe, rgdpo, pop)
df_polity <- polity%>%dplyr::select(country, year, polity, polity2, p5, democ, autoc)
# Create a new variable 'iso' containing ISO codes for each country
df_polity$isocode <- countrycode(sourcevar = df_polity$country,
                          origin = "country.name",
                          destination = "iso3c")

#merging the following datasets
df_merged <- merge(df_penn_world, df_polity, by=c("isocode", "year"))
#not sure about this -- see the polity handbook for what -11, -66, and -88 mean
df_merged <- df_merged %>% filter(polity>-11)

#Add regions for each country in the dataset
df_merged$region <- countrycode(sourcevar = df_merged$country.x,
                             origin = "country.name",
                             destination = "region")
df_merged$isocode <- as.character(df_merged$isocode)
str(df_merged$isocode)

#adding a basic per capita gdp metric
df_merged$per_cap_gdp <- (df_merged$rgdpna*1000000)/(df_merged$pop*1000000)

#separating Europe from Central Asia
df_merged$region <- ifelse(df_merged$isocode=="KAZ" | df_merged$isocode=="TJK" | df_merged$isocode=="UZB" | df_merged$isocode=="TKM" | df_merged$isocode=="KGZ", "Central Asia", df_merged$region)
df_merged$region <- ifelse(df_merged$region=="Europe & Central Asia", "Europe",df_merged$region)
str(df_merged$europe)

#creating the Europe and North America Dataset
df_na_europe <- df_merged %>% filter(region=="Europe" | region=="North America")
df_na_europe$country.x <- as.character(df_na_europe$country.x)
unique(df_na_europe$country.x)

#test graph for formatting
ggplot(df_na_europe %>% filter(isocode == "FRA"), aes(x=rgdpna, y=polity)) + ylim(-10,10) +
  geom_point(color="#69b3a2", size=2) +
  ggtitle("Table: Polity2 Score by Real Nominal GDP") +
  theme_ipsum()

isocode <- unique(df_na_europe$isocode)
plot_list <- list()
#basic loop in ggplot2
for (i in isocode) {
    # Generate a graph for the current country and year
  pl <- ggplot(df_na_europe %>% filter(isocode==i), aes(x = per_cap_gdp/1000, y = polity)) + ylim(-10,10) + geom_line() + 
    ggtitle(paste("Polity Score for", df_na_europe$country.x, "given a value of real nominal per capita GDP"))
  print(pl) 
  #store the plot in the list with id as the name
  plot_list[[as.character(i)]] <- pl
}

pdf('graphs/graph.pdf')
pdf.options(width = 9, height = 7)
for (i in 1:length(plot_list)){
  print(plot_list[[i]])
}
```

```{r, include=FALSE, results='asis'}
#code for graphs with two y axes --> the gdp value is at the 100thousandth level to allow for easy comparison between polity score and gdp
#setting the graph 
coef <- 1000

#code for China - can make a loop of this later
df_merged %>% filter(country.x=="Japan")%>%
  ggplot(., aes(x = year)) + 
  #First Y Axis
  geom_line(aes(y=polity2), col="blue", size=2) + 
  geom_line(aes(y=per_cap_gdp/10000), col = "red", size=2) +
  scale_y_continuous(name="Polity Score", limits = c(-10, 10), expand=c(.1,.1), sec.axis = sec_axis(~.*10000, name="GDP per capita"),
                     labels = function(x) format(x, scientific = FALSE)) + 
  ggtitle("Graph comparing polity score and gdp per capita value of China") + 
  theme(axis.title.y = element_text(color = "blue", size=13), axis.title.y.right = element_text(color = "red", size=13))
```
